In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [3]:
A = np.random.randn(100) #100個 N(0,1)

In [4]:
A

array([  1.62147398e-01,  -2.56922448e-01,   8.34706818e-01,
         4.80972302e-01,  -6.81357961e-02,   1.30224636e+00,
        -1.30178777e+00,   2.00952863e-01,   1.67029988e+00,
         4.01499304e-01,   1.56588317e+00,  -3.36552978e-01,
         1.16243253e+00,   2.98112871e-01,  -1.63361181e+00,
        -1.66066200e-01,  -8.94339798e-01,  -9.54142601e-01,
        -5.07986829e-02,  -1.69721359e+00,   7.36297441e-02,
        -1.56139270e+00,   4.53272580e-02,  -6.07998305e-01,
         1.45228091e+00,   2.93463921e-01,  -1.28842426e+00,
        -4.18260668e-01,  -2.12346448e+00,   5.10360465e-01,
         1.04535284e+00,   3.84679643e-01,  -1.99572350e+00,
        -1.30940074e-01,  -9.77428832e-01,  -7.56063319e-01,
        -4.40465857e-01,  -8.45775700e-01,  -7.09731341e-01,
        -1.12940347e+00,  -9.32577631e-01,  -1.53771881e-01,
         4.18655445e-01,   2.03980362e+00,   9.62892848e-01,
        -2.22999718e-01,   1.70500213e+00,   4.45079612e-01,
         4.69791463e-01,

In [5]:
A = 10*A+50   #變成 N(50,10)

In [6]:
A

array([ 51.62147398,  47.43077552,  58.34706818,  54.80972302,
        49.31864204,  63.02246359,  36.98212233,  52.00952863,
        66.70299878,  54.01499304,  65.65883175,  46.63447022,
        61.62432534,  52.98112871,  33.66388194,  48.339338  ,
        41.05660202,  40.45857399,  49.49201317,  33.02786411,
        50.73629744,  34.38607303,  50.45327258,  43.92001695,
        64.52280907,  52.93463921,  37.11575738,  45.81739332,
        28.76535521,  55.10360465,  60.45352843,  53.84679643,
        30.04276499,  48.69059926,  40.22571168,  42.43936681,
        45.59534143,  41.542243  ,  42.90268659,  38.70596531,
        40.67422369,  48.46228119,  54.18655445,  70.39803619,
        59.62892848,  47.77000282,  67.0500213 ,  54.45079612,
        54.69791463,  26.84128183,  44.54205838,  56.02785513,
        41.13159239,  43.84494206,  49.62427768,  52.96495088,
        49.13511001,  47.23344477,  40.19376574,  69.53129547,
        47.93676457,  57.45993262,  46.94252613,  62.58

In [7]:
A.shape

(100,)

In [8]:
A.shape = (5, 20)   # 更改 array形狀的方法 array.shape = (新的形狀)

In [9]:
A

array([[ 51.62147398,  47.43077552,  58.34706818,  54.80972302,
         49.31864204,  63.02246359,  36.98212233,  52.00952863,
         66.70299878,  54.01499304,  65.65883175,  46.63447022,
         61.62432534,  52.98112871,  33.66388194,  48.339338  ,
         41.05660202,  40.45857399,  49.49201317,  33.02786411],
       [ 50.73629744,  34.38607303,  50.45327258,  43.92001695,
         64.52280907,  52.93463921,  37.11575738,  45.81739332,
         28.76535521,  55.10360465,  60.45352843,  53.84679643,
         30.04276499,  48.69059926,  40.22571168,  42.43936681,
         45.59534143,  41.542243  ,  42.90268659,  38.70596531],
       [ 40.67422369,  48.46228119,  54.18655445,  70.39803619,
         59.62892848,  47.77000282,  67.0500213 ,  54.45079612,
         54.69791463,  26.84128183,  44.54205838,  56.02785513,
         41.13159239,  43.84494206,  49.62427768,  52.96495088,
         49.13511001,  47.23344477,  40.19376574,  69.53129547],
       [ 47.93676457,  57.45993262,  

In [11]:
A.reshape(100,1) #產生新 array 不改變原來的
A = A.reshape(100,1) #這樣才可以不改變原來的